a

diff --git a/.github/workflows/auto_saferollout.yml b/.github/workflows/auto_saferollout.yml
--- a/.github/workflows/auto_saferollout.yml
+++ b/.github/workflows/auto_saferollout.yml
@@ -17,7 +17,7 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
     outputs:
-      first_run: ${{ steps.create_initial_prod.outputs.first_run }}
+      NOT_FIRST_RUN: ${{ steps.create_initial_prod.outputs.NOT_FIRST_RUN }}
     steps:
     - name: Configure endpoint files
       run: |
@@ -50,8 +50,7 @@ jobs:
         echo "LATEST_MODEL=$LATEST_MODEL" >> $GITHUB_ENV
     # step 1: validation and day1 scenarios
     - name: Step 1a-If endpoint does not exist, create
-      run: |
-        az ml online-endpoint create --name ${{secrets.ENDPOINT_NAME }} -f ${{ env.ENDPOINT_FILE }}
+      run: |        
         export ENDPOINT_EXISTS=$(az ml online-endpoint list -o tsv --query "[?name=='${{secrets.ENDPOINT_NAME }}'][name]" |  wc -l)
         if [[ ENDPOINT_EXISTS -ne 1 ]]; then
           az ml online-endpoint create -n ${{secrets.ENDPOINT_NAME }} -f ${{ env.ENDPOINT_FILE }}          
@@ -65,39 +64,36 @@ jobs:
       run: |        
         # Get the name of prod deployment
         export PROD_DEPLOYMENT=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT")
-        echo PROD DEPL is $PROD_DEPLOYMENT
-        echo size ${#PROD_DEPLOYMENT}
-        echo 1111
-        az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query "tags.PROD_DEPLOYMENT"
-        echo 2222
-        az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }}
-
         echo "PROD_DEPLOYMENT=$PROD_DEPLOYMENT" >> $GITHUB_ENV
         if [[ -z "$PROD_DEPLOYMENT" ]]; then
           echo "prod deployment does not exist - creating it"
           export PROD_DEPLOYMENT=${{ env.RC_DEPLOYMENT_NAME }}
           az ml online-deployment create --name ${{ env.RC_DEPLOYMENT_NAME }} --endpoint ${{secrets.ENDPOINT_NAME }} -f ${{ env.DEPLOYMENT_FILE }} --all-traffic --set model=${{ env.LATEST_MODEL }}
           az ml online-endpoint update --name ${{secrets.ENDPOINT_NAME }} --set tags.PROD_DEPLOYMENT=$PROD_DEPLOYMENT          
-          echo "It is expected to fail in the first run since we want to stop after deployment creation as there is no saferollout (since github action does not allow with exit 0)"
-          echo "::set-output name=first_run::true"
+          echo "It is expected to fail in the first run since we want to stop after deployment creation as there is no saferollout (since github action does not allow with exit 0)"          
           # github action does not allow with exit 0.
-          exit 1
+          #exit 1
         else # validate if PROD  has 100%.
           echo "validating if prod as 100%"
           export PROD_TRAFFIC=$(az ml online-endpoint show -n ${{secrets.ENDPOINT_NAME }} -o tsv --query traffic.$PROD_DEPLOYMENT)
-          if [[ $PROD_TRAFFIC -ne '100' ]]; then echo "Error: For this saferollout script to start, traffic to prod deployment needs to be 100%"; exit 1; fi   
+          if [[ $PROD_TRAFFIC -ne '100' ]]; then echo "Error: For this saferollout script to start, traffic to prod deployment needs to be 100%"; exit 1; fi  
+
+          echo "::set-output name=NOT_FIRST_RUN::true"
+          echo "NOT_FIRST_RUN=$NOT_FIRST_RUN" >> $GITHUB_ENV
         fi
     - name: Step 2-Create RC deployment
+      if: ${{ env.NOT_FIRST_RUN }}
       run: |          
         az ml online-deployment create --name ${{ env.RC_DEPLOYMENT_NAME }} --endpoint ${{secrets.ENDPOINT_NAME }} -f ${{ env.DEPLOYMENT_FILE }} --all-traffic --set model=${{ env.LATEST_MODEL }}
          
     - name: Step 3-Divert 10% traffic to RC
+      if: ${{ env.NOT_FIRST_RUN }}
       run: | 
         az ml online-endpoint update -n ${{secrets.ENDPOINT_NAME }} --traffic ${{ env.PROD_DEPLOYMENT }}:90,${{ env.RC_DEPLOYMENT_NAME }}:10
 
   rollout_50pct_traffic:
     needs: [rollout_10pct_traffic, validate_errors_within_threshold_10pct_traffic, validate_latency_within_threshold_10pct_traffic]
-    if: ${{ needs.rollout_10pct_traffic.outputs.first_run }}
+    if: ${{ needs.rollout_10pct_traffic.outputs.NOT_FIRST_RUN }}
     name: Rollout 50% traffic    
     runs-on: ubuntu-latest
     steps:
